name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    name: Build and Release Electron App
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.5.0"


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure Python for Windows
        if: runner.os == 'Windows'
        run: |
          npm config set python "C:\\hostedtoolcache\\windows\\Python\\3.11.*/x64/python.exe"
           echo "PYTHON=C:\\hostedtoolcache\\windows\\Python\\3.11.*/x64/python.exe" >> $env:GITHUB_ENV   

      - name: Install Linux dependencies for pacman build
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools fakeroot rpm dpkg tar xz-utils build-essential

      - name: Install Dependencies
        run: npm install

      - name: Rebuild native modules for Electron
        run: npx electron-rebuild

      - name: Build Electron App
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: release
