name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    name: Build and Release Electron App
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4  # ✅ 更新为 v4

      - name: Install Node.js
        uses: actions/setup-node@v4  # ✅ 更新为 v4
        with:
          node-version: "23.5.0"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist/!(*.exe)"

      - name: Cleanup Artifacts for macOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "dist/!(*.dmg)"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # ✅ 更新为 v4
        with:
          name: ${{ matrix.os }}
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2  # ✅ 更新为 v2（v0.1.14 已过时）
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
